set encoding=utf-8

" Leader
let mapleader = " "

" 2 spaces for indentation.
" More information: http://vimcasts.org/episodes/tabs-and-spaces/
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

" Enable line numbers
set number

" Disable swap
set noswapfile

" Mouse scrolling works as expected in Tmux
set mouse=a

" Open new split panes to right and bottom, which feels more natural
set splitbelow
set splitright

" ctags
set tags=tags

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Automatically install vim-plug if it does not exist.
" Credit: https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins
" Note: plug#end automatically executes `filetype plugin indent on` 
" and `syntax enable`, so no need to declare them again.
call plug#begin('~/.vim/plugged')
  " General
  Plug 'ctrlpvim/ctrlp.vim'
  Plug 'mileszs/ack.vim'
  Plug 'tpope/vim-surround'
  Plug 'dense-analysis/ale'
  Plug 'AndrewRadev/splitjoin.vim'
  Plug 'tpope/vim-fugitive'
  Plug 'tpope/vim-rhubarb'
  Plug 'christoomey/vim-conflicted'
  Plug 'airblade/vim-gitgutter'
  Plug 'tpope/vim-projectionist'
  Plug 'tpope/vim-dispatch'
  Plug 'janko/vim-test'
  Plug 'sheerun/vim-polyglot'

  " Ruby
  Plug 'vim-ruby/vim-ruby'
  Plug 'tpope/vim-rails'

  " Javascript
  Plug 'pangloss/vim-javascript'
  Plug 'MaxMEllon/vim-jsx-pretty'
  Plug 'jxnblk/vim-mdx-js'
  Plug 'tpope/vim-commentary'
  Plug 'scrooloose/nerdtree'
  Plug 'slim-template/vim-slim'
  Plug 'hashivim/vim-terraform'
  Plug 'tpope/vim-repeat'
  Plug 'leafgarland/typescript-vim'
  Plug 'Quramy/tsuquyomi'
call plug#end()

" Colorscheme 
if (has("termguicolors"))
  set termguicolors
endif

syntax on

" ALE global configuration
let g:ale_fix_on_save = 1

" Vim signify colours
highlight DiffAdd           cterm=bold ctermbg=none ctermfg=119
highlight DiffDelete        cterm=bold ctermbg=none ctermfg=167
highlight DiffChange        cterm=bold ctermbg=none ctermfg=227

" Vim test
nnoremap <silent> <Leader>tf :TestFile<CR>
nnoremap <silent> <Leader>tn :TestNearest<CR>
nnoremap <silent> <Leader>tl :TestLast<CR>
nnoremap <silent> <Leader>ts :TestSuite<CR>
nnoremap <silent> <Leader>tv :TestVisit<CR>

let test#strategy = 'vimterminal'

" NERDTree
nnoremap <Leader>nt :NERDTreeToggle<CR>
nnoremap <Leader>nf :NERDTreeFind<CR>

" Navigate the quickfix list
nnoremap <Leader>qn :cn<CR>
nnoremap <Leader>qp :cp<CR>

" Respect .gitignore using CtrlP
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']

" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

" Bind backslash (\) to Ack
nnoremap \ :Ack!<SPACE>

" Local config
nnoremap <Leader>z0 :e ~/Dev/dotfiles/shell/vimrc<CR>
nnoremap <Leader>z1 :e ~/.vimrc.local<CR>
nnoremap <Leader>z2 :e ~/Dev/dotfiles/shell/zshrc<CR>
nnoremap <Leader>z3 :e ~/.zshrc.local<CR>
nnoremap <Leader>z4 :e ~/Dev/dotfiles/shell/gvimrc<CR>
nnoremap <Leader>s0 :source ~/.vimrc<CR>
nnoremap <Leader>s1 :source ~/.gvimrc<CR>

nnoremap <silent> <Leader>zf :cd ~/Dev/dotfiles <bar> :e install.conf.yaml<CR>

if filereadable($HOME . "/.vimrc.local")
  source ~/.vimrc.local
endif
