# vim: set syntax=sh 

# Homebrew: dependencies take precedence
export PATH=$HOME/bin:/usr/local/bin:$PATH

# homebrew binaries are available in path
export PATH="/usr/local/sbin:$PATH"

# Load nvm's nodejs
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"
# export PATH="/Users/muyiwa/.nvm/versions/node/v15.8.0/bin:$PATH"
