brew "git"
brew "hub"
brew "zsh"
brew "zsh-completions"
brew "fzf"
brew "the_silver_searcher"
brew "rbenv"
brew "ruby-build"
brew "tmux"
brew "diff-so-fancy"
brew "ctags"

tap "thoughtbot/formulae"
brew "rcm"

brew "mas"
mas "Magnet", id: 441258766

cask "vimr"
cask "iTerm2"
cask "google-chrome"
cask "1Password"
cask "gpg-suite"

tap "homebrew/cask-fonts"
cask "font-fira-code"
